### ISSUE TITLE
[Filter field] Distinct option does not work

### ISSUE THREAD

**Issue by seilmsteiner** [dynatrace-oss/barista#1547] opened 2020-09-02 07:56 UTC
# Bug Report
The distinct option on the filter field does not work if the selected filter value is no longer in the autocomplete list. Then it is still possible to add another filter of this category. 

## Expected Behavior
If the distinct option is applied, the filter field should not allow another filter of this category in any situation. 

## Current Behavior

It is possible to apply to filters of the same category, although distinct=true is set. 

## Possible Solution

Only a workaround: 
add the applied filters always to the suggestion list

## Steps to Reproduce

- https://stackblitz.com/edit/github-1hiynz?file=src%2Ffilter-field%2Ffilter-field-partial-example%2Ffilter-field-partial-example.ts

- add filter "AUT" - "Linz"
- after the filter is applied I change the suggestion list in the method filterChanged(..)
- then it is possible to add another filter of "AUT"

## Context (Environment)
In Memory Profiling: 
- we update the suggestion list, as soon as a filter is set. (e.g.: set "Type"-filter, then set "API"-filter and then we update the suggestion list for the Type filter and it could happen that the type filter is not in the suggestion list any more)  
- lazy loading: we limit the suggestion list to 100 entries, if you select something from outside the top 100 it is not in the suggestion list any more

**Comment by rowa-audil** [comment] 2020-10-01 09:48
@thomaspink @lukasholzer 
How about dropping the filter tags, when the datasource changes. It doesn't make sense to have a filter that doesn't filter based on the datasource?

**Comment by rowa-audil** [comment] 2020-10-01 09:50
@seilmsteiner

So in that case you would need to drop the previous TYPE filters for the updated one?
Or do you need the filtered tag from the old TYPE after you updated too?

**Comment by rowa-audil** [comment] 2020-10-01 13:07
**Investigation results:**

- The actual behavior should be like that. The distinct option does not apply to multiple data sources but to one.
The definition of distinct is concerning one autocomplete.
- In @seilmsteiner's case the problem is a bit different since it concerns a changing data source. Short summary:
Pick the first filter `e.g: TYPE: string (out of string, number)` then the second `e.g: API: 'anything'` which results in the available TYPE filter options to change `e.g:  TYPE has only number as an option now`
- Now the issue is that it should be distinct but since the distinct option doesn't concern changing data sources, the user can pick TYPE again

IMO this issue is a feature request.

What is your opinion on that? @thomaspink @tomheller @lukasholzer

**Comment by rowa-audil** [comment] 2020-10-02 06:17
Closing this issue as it is not a bug nor a feature request.

**Closed by rowa-audil** 2020-10-02 06:17 UTC
Labels: bug, filter-field, needs discussion

**Comment by rowa-audil** [comment] 2020-10-02 06:31
**Through the investigation the following this came up:**

> **Investigation results:**
> 
> The actual behavior should be like that. The distinct option does not apply to 'multiple changing' data sources but to one.
> The definition of distinct concerns one autocomplete or data source.
> 
> In @seilmsteiner's case, the problem is a bit different since it concerns a changing data source. Short summary:
> Pick the first filter `e.g: TYPE: 'string' (out of string, number)` then the second `e.g: API: 'anything'` which results in the available TYPE filter options to change `e.g: TYPE has only 'number' as an option now`
> 
> Now the issue is that it should be distinct but since the distinct option doesn't concern changing data sources, the user can pick TYPE with new options again
> 

**Why is this issue closed?:**

As it turns out the filter field component doesn't support multiple datasources, since the probability of remembering old data causing memory leaks is too high. @seilmsteiner's issue is a special use-case for his project in a very specific manner and we can not handle such specific use-cases on our side. 
_Possible workaround_ would be: Datasources should not be reassigned but `next()'ed`, so the distinct option applies as it doesn't distinguish between multiple reassigned datasources.
