### ISSUE TITLE
Filter Field: Add NOT operator

### ISSUE THREAD

**Issue by ffriedl89** [dynatrace-oss/barista#97] opened 2019-11-13 11:20 UTC
NOT operator is optional - set by dev somehow 
if not operator is present - show operators between filters, e.g. request < 10s AND some > 10 AND NOT 
line breaks should not happen between operator and filter
operator should be changeable 
operator should be focusable
operator and filter should be editable independently

This issue needs more discussion, we are adding more and more functionality that goes towards a query language - so why not use a query language field for those complex queries

**Comment by tomheller** [comment] 2020-01-08 08:00
Duplicate of #283

**Closed by tomheller** 2020-01-08 08:00 UTC
Labels: P3, feature, needs discussion
