### ISSUE TITLE
key-value-list only shows one column in Safari

### ISSUE THREAD

**Issue by davidHaunschmied** [dynatrace-oss/barista#1756] opened 2020-10-20 12:49 UTC
# Bug Report

## Expected Behavior

When opening the following example in Safari, I expect to see the two configured columns of the key-value-list.
https://github-jrb9yd.stackblitz.io/

## Current Behavior

Only the first column is shown. Although, two columns are configured: https://stackblitz.com/edit/github-jrb9yd?file=src/key-value-list/key-value-list-default-example/key-value-list-default-example.html

## Steps to Reproduce

1. Open https://github-jrb9yd.stackblitz.io/ in Safari.

### Used Versions:

- Safari Version 13.1.1 (15609.2.9.1.2)
- https://stackblitz.com/edit/github-jrb9yd?file=package.json

## Attachments
<img width="1496" alt="Bildschirmfoto 2020-10-20 um 14 37 25" src="https://user-images.githubusercontent.com/6122758/96588063-708b8500-12e3-11eb-8fa1-0c17ee7e0c1a.png">

**Comment by lukasholzer** [comment] 2020-10-21 07:05
Thx for reporting the issue. @davidHaunschmied do you mean the key-value list? Your headline states a different component.
Do you want to contribute the fix to the library?

**Comment by davidHaunschmied** [comment] 2020-10-21 07:07
Yes, sorry. I corrected the headline.

**Comment by tomheller** [comment] 2020-10-23 05:59
This is quite interesting and does seem like safari having a bug regarding css-columns here. 

In safari 12, it still works:

![safari-12](https://user-images.githubusercontent.com/6338434/96961732-92fce880-1505-11eb-86be-b2547f0259d3.gif)

In safari 13, it does not work any more: 

![Safari-13](https://user-images.githubusercontent.com/6338434/96961743-9a23f680-1505-11eb-8781-80aab4a2f7ad.gif)

Although the element seems to be rendered in the correct position when looking at it in the inspector:
![image](https://user-images.githubusercontent.com/6338434/96961647-65b03a80-1505-11eb-910f-a0b86521bc4d.png)

**Comment by SkaillZ** [comment] 2020-10-27 13:11
Seems to work in Safari 14 too.

**Comment by ffriedl89** [comment] 2020-10-28 08:01
Closing due to Safari regression that is fixed in Safari 14 again.

**Closed by ffriedl89** 2020-10-28 08:01 UTC
Labels: bug
