### ISSUE TITLE
Inconsistencies in interacting with Chart heatfiled/selection Area and ContextDialog

### ISSUE THREAD

**Issue by sherifElhefnawyDynatrace** [dynatrace-oss/barista#725] opened 2020-03-12 09:03 UTC
# Bug Report

## Current Behavior

The following components seem to have different behaviors when it comes to how the user can close them:

Context Dialog
Chart Selection Area
Chart Heatfield

### Context Dialog:

- User is presented with an X button to close it
- User can click outside the dialog to close it
- User can press "ESC" on the keyboard to close it

![image](https://user-images.githubusercontent.com/59170440/76504219-9399b080-6447-11ea-8524-595ee521a511.png)

### Chart Selection Area

- User is presented with an X button to close it
- Clicking outside the dialog or chart **doesn't** close it
- Pressing "ESC" on the keyboard **doesn't** close it

![image](https://user-images.githubusercontent.com/59170440/76504314-c5ab1280-6447-11ea-8e64-2ad19a161884.png)

### Chart HeatField

- User can click on the red bar to close it
- User is **NOT** presented with an X button
- Clicking outside the dialog or chart **doesn't** close it
- Pressing "ESC" on the keyboard **doesn't** close it

![image](https://user-images.githubusercontent.com/59170440/76504506-263a4f80-6448-11ea-982a-aecbdab0d933.png)

### Summary

Would love to know why are there differences in behavior when it comes to closing the three overlays discussed.

**Comment by ffriedl89** [comment] 2020-03-12 12:18
I think these are valid questions. I think we can argue that the context dialog is a temporary interaction that should be dismissed once the user wants to interact with anything else on the page.
The selection area has a different use case in addition to the analyze drilldown button - it is also used for filtering data right away. Therefore closing it when interacting with anything else on the page would break the filtering use case.
But the heatfield is a bit problematic for me - and I can't find a good reasoning for the behavior as it is right now. 

@dynatrace-oss/ux-core Please help us here 😄

**Comment by perihan-rashed** [comment] 2020-03-12 13:31
@ffriedl89  I already talked to Kathrin Aigner (the component owner), and back then they did not consider the accessibility topic. Therefore, she approved on adding an "x" to the heat-field tooltip. 
Regarding closing when clicking outside according to @lukasholzer there is a function that can be  used (see attahctment), which would allow us to close when clicking outside. (since we don't have the filtering use-case) 
![method](https://user-images.githubusercontent.com/62100118/76526554-00c03c80-646e-11ea-9992-ef71d63df59f.png)

**Comment by ffriedl89** [comment] 2020-03-12 13:36
@perihan-rashed thanks for clarifying! So an action item would be to create a ticket to add a closing button also to the heatfield overlay by default :) I will create a separate issue for that and I think we can close this one.

**Comment by perihan-rashed** [comment] 2020-03-12 13:37
@ffriedl89 awesome thank you !

**Comment by sherifElhefnawyDynatrace** [comment] 2020-03-12 13:38
And as for the clicking outside? Should that behavior also be in Chart Heatfield and Chart SelectionArea? @perihan-rashed

**Comment by perihan-rashed** [comment] 2020-03-16 07:39
Confirmed with the component owner and it should close with ESC but not when clicking outside.

**Comment by sherifElhefnawyDynatrace** [comment] 2020-03-16 08:21
@ffriedl89 , so let's close this issue and create another issue for the ESC button behavior for both heatField and selectionArea

**Closed** 2020-03-16 08:29 UTC
Labels: bug, needs discussion
