### ISSUE TITLE
[FilterField] Not validating when blur without value

### ISSUE THREAD

**Issue by obarcelonap** [dynatrace-oss/barista#1444] opened 2020-08-05 11:09 UTC
# Bug Report

## Current Behavior

When the user adds a filter of type freetext and then looses the focus (without adding the value nor typing anything) it does not show the validation error

## Expected Behavior

Show the validation error (if applies) when blur if there is no value

## Steps to Reproduce

reproducible here https://stackblitz.com/edit/dt-filter-field-requried-free-text?file=src%2Ffilter-field%2Ffilter-field-validator-example%2Ffilter-field-validator-example.ts

**Comment by tomheller** [comment] 2020-08-05 12:09
The value is not submitted, when the filter-field is blurred. It is considered in flight and not submitted at that point. We do not want to show a validation at this point, because the user could just move over to some other text to copy it. 

We show the validation if the user tries to submit the value or starts typing a text and removes everything again... This behaviour is by design.

**Comment by ffriedl89** [comment] 2020-08-05 12:51
@obarcelonap I am sorry about me bugging you to open an issue. I double checked also the behavior of the input field and it behaves the same way as the filter field does. Also see this page:  https://barista.dynatrace.com/patterns/validation for details. 

I am closing the issue since this works as designed after double checking.

**Closed by ffriedl89** 2020-08-05 12:51 UTC
Labels: bug
