### ISSUE TITLE
[Button Group]: Selection does not work when items are rendered with *ngFor when no value is given

### ISSUE THREAD

**Issue by tomheller** [dynatrace-oss/barista#1142] opened 2020-06-09 05:51 UTC
# Bug Report

## Expected Behavior

When generating the buttons in a button group in the template with ngFor, one would expect them to behave the same as if they would be hardcoded.

## Current Behavior

When using ngFor to create the button-group-items, the buttons are no longer selectable (or as can be seen within the example, are treated as a single entity).
```html
<dt-button-group>
  <dt-button-group-item *ngFor='let tab of buttons | keyvalue'>{{ tab.key }}</dt-button-group-item>
</dt-button-group>
```

## Steps to Reproduce

1. Open this stackblitz example](https://stackblitz.com/edit/github-wkqd8v?file=src%2Fbutton-group%2Fbutton-group-default-example%2Fbutton-group-default-example.html) and click `Hardcoded` -> the hardcoded button gets selected. 
2. Then click any of the other buttongroup buttons again, all of the ones that are built with ngFor are now selected.

*Addendum*: This can be fixed by binding a value to each of the buttons, but does not have to be done when not using ngFor. [Fixed stackblitz example](https://stackblitz.com/edit/github-wkqd8v-to2c9k?file=src/button-group/button-group-default-example/button-group-default-example.html)

### Used Versions:

- **angular**: 9.1.9
- **@angular/cdk**: 9.2.4
- **@dynatrace/barista-components**: 7.0.1

**Comment by rowa-audil** [comment] 2020-09-08 06:36
This bug is not reproducible in the current version of our repo? I'll update the dependencies in the Stackblitz examples to and figure out what dependency needs to be updated.

**Comment by rowa-audil** [comment] 2020-09-08 12:41
Using the `@dynatrace/barista-components` with version `8.0.0` would solve this issue.

**Comment by tomheller** [comment] 2020-09-08 13:06
https://stackblitz.com/edit/github-wkqd8v?file=src%2Fbutton-group%2Fbutton-group-default-example%2Fbutton-group-default-example.html

This is still an issue, even after the version update.
You should be able to reproduce this problem on your local installation.

**Comment by rowa-audil** [comment] 2020-09-09 09:39
@tomheller I don't understand why ivy has a role in that since we don't have ivy enabled yet. And apparently the Stackblitz example also doesn't

**Comment by tomheller** [comment] 2020-09-09 10:16
It was just a guess. It could also be AOT vs JIT compilation. But the issue is definitely reproducible in stackblitz and not solved with v8 of the components.

**Comment by rowa-audil** [comment] 2020-09-29 13:48
https://stackblitz.com/edit/button-group-bug-fix-2?file=tsconfig.json

Seems like Ivy is the cause of this issue, but I'll have to investigate further.
Set `enableIvy: false` & `aot: false` and it will work

**Comment by rowa-audil** [comment] 2020-09-30 08:23
Investigation to this point:

The button group selection bug is fixed when using IVY and the consensus in the team is to wait for Angular's major upgrade. The new version will drop Viewengine and opt for IVY.

Here is a Stackblitz example of the button-group with ivy enabled:
https://stackblitz.com/edit/button-group-bug-ivy?file=tsconfig.json

Disable ivy (`enableIvy: false`) and behaves wrong.

**Comment by rowa-audil** [comment] 2020-10-02 08:42
Closing this issue. This issue is caused by ViewEngine and is solved by using Ivy.



> Investigation to this point:
> 
> The button group selection bug is fixed when using IVY and the consensus in the team is to wait for Angular's major upgrade. The new version will drop Viewengine and opt for IVY.
> 
> Here is a Stackblitz example of the button-group with ivy enabled:
> https://stackblitz.com/edit/button-group-bug-ivy?file=tsconfig.json
> 
> Disable ivy (`enableIvy: false`) and behaves wrong.

**Closed by rowa-audil** 2020-10-02 08:42 UTC
Labels: Hacktoberfest 🎃, bug
