### ISSUE TITLE
[filter-field] Input is not cleared when another filter is selected

### ISSUE THREAD

**Issue by rarenal** [dynatrace-oss/barista#1688] opened 2020-10-02 13:28 UTC
# Bug Report
When the user is typing to select a filter in the filter field, if another filter is selected, then the written text remains,

## Expected Behavior
The text is cleaned when a different filter is selected

## Steps to Reproduce
Reproducible in the basic example: https://stackblitz.com/github/dynatrace-oss/barista-examples/tree/master/examples/DtExampleFilterFieldDefault/

Screenshots with the issue: 
![image](https://user-images.githubusercontent.com/11938799/94927641-dcd44f00-04c2-11eb-8b52-d4bf90068eee.png)
<img width="359" alt="Screen Shot 2020-10-02 at 3 21 37 PM" src="https://user-images.githubusercontent.com/11938799/94928319-cda1d100-04c3-11eb-8697-4222a38412bd.png">
![image](https://user-images.githubusercontent.com/11938799/94927770-042b1c00-04c3-11eb-8f00-8e23ba0cef04.png)

**Comment by lukasholzer** [comment] 2020-10-05 07:36
This is a duplicate of #1572

**Closed by lukasholzer** 2020-10-05 07:36 UTC
Labels: bug
